/**
 * The organization's outbound webhook. See
 * docs/CRUD-MIGRATION-REFERENCE.md §1.14.
 *
 * ### A singleton, so there is no id
 *
 * One organization has one webhook. `GET /webhook` reads it and `PUT /webhook`
 * upserts it — there is no collection to page through and no `{id}` in either
 * path, which is why this module is hand-rolled rather than generated by the
 * CRUD factory.
 */
export type Webhook = {
  /** Where events are POSTed. Empty string when none is configured yet. */
  url: string
  /**
   * The header name and value the backend signs each delivery with — the
   * receiving end compares them to authenticate the call. Both are generated
   * server-side and read-only here; the form only ever sets the URL.
   */
  secretKey: string
  secretValue: string
  /** Always `POST` in practice. Read back rather than assumed. */
  method: string
}

/**
 * `PUT /webhook` → `{ webhook_url }`.
 *
 * **Asymmetric with the read on purpose**: the response calls the field `url`
 * and the request calls it `webhook_url`. Sending `{ url }` is accepted and
 * ignored, so the mismatch fails silently — the save appears to work and the
 * endpoint keeps whatever it had.
 */
export type UpdateWebhookInput = {
  webhookUrl: string
}
