/**
 * Sample Members Requests data.
 *
 * Placeholder only — replace with the real API once request endpoints exist.
 * Shapes follow the ID-request flow described in docs/dashboard-overview.md:
 * a member submits a request, it is routed through a branch/node, reviewed,
 * then paid, printed, and delivered.
 */

export type RequestStatus =
  | "pending"
  | "in_review"
  | "approved"
  | "printing"
  | "delivered"
  | "rejected"

export type RequestPriority = "high" | "medium" | "low" | "none"

export type MemberRequest = {
  id: string
  memberName: string
  memberEmail: string
  /** Index into the shared avatar gradient set (§2.2). */
  avatar: number
  template: string
  branch: string
  status: RequestStatus
  priority: RequestPriority
  /** ISO date, or null for an unset field — renders as "Add date" (§8.6). */
  submittedAt: string
  dueAt: string | null
  amount: number
  /** 0–100; drives the segmented meter (§8.6). */
  progress: number
  reviewers: number[]
}

export const STATUS_META: Record<
  RequestStatus,
  { label: string; tone: "neutral" | "info" | "success" | "warning" | "danger" }
> = {
  pending: { label: "Pending", tone: "neutral" },
  in_review: { label: "In review", tone: "info" },
  approved: { label: "Approved", tone: "success" },
  printing: { label: "Printing", tone: "warning" },
  delivered: { label: "Delivered", tone: "success" },
  rejected: { label: "Rejected", tone: "danger" },
}

export const PRIORITY_META: Record<
  RequestPriority,
  { label: string; tone: "neutral" | "info" | "success" | "danger" }
> = {
  high: { label: "High", tone: "danger" },
  medium: { label: "Medium", tone: "info" },
  low: { label: "Low", tone: "success" },
  none: { label: "Not set", tone: "neutral" },
}

/** Order used when grouping by status (§8.4). */
export const STATUS_ORDER: RequestStatus[] = [
  "pending",
  "in_review",
  "approved",
  "printing",
  "delivered",
  "rejected",
]

export const requests: MemberRequest[] = [
  {
    id: "REQ-4821",
    memberName: "Layla Hassan",
    memberEmail: "layla.hassan@ministry.gov",
    avatar: 1,
    template: "Staff ID — Ministry",
    branch: "Baghdad Central",
    status: "pending",
    priority: "high",
    submittedAt: "2026-08-04",
    dueAt: "2026-08-26",
    amount: 25000,
    progress: 10,
    reviewers: [2, 4],
  },
  {
    id: "REQ-4822",
    memberName: "Omar Khalid",
    memberEmail: "omar.k@ministry.gov",
    avatar: 2,
    template: "Staff ID — Ministry",
    branch: "Baghdad Central",
    status: "in_review",
    priority: "medium",
    submittedAt: "2026-08-04",
    dueAt: "2026-08-27",
    amount: 25000,
    progress: 45,
    reviewers: [1, 3, 5],
  },
  {
    id: "REQ-4823",
    memberName: "Sara Abdullah",
    memberEmail: "s.abdullah@univ.edu.iq",
    avatar: 3,
    template: "Student ID — Spring",
    branch: "Basra Campus",
    status: "approved",
    priority: "low",
    submittedAt: "2026-08-05",
    dueAt: "2026-08-28",
    amount: 15000,
    progress: 70,
    reviewers: [4],
  },
  {
    id: "REQ-4824",
    memberName: "Yusuf Ibrahim",
    memberEmail: "yusuf.ibrahim@univ.edu.iq",
    avatar: 4,
    template: "Student ID — Spring",
    branch: "Basra Campus",
    status: "printing",
    priority: "medium",
    submittedAt: "2026-08-05",
    dueAt: null,
    amount: 15000,
    progress: 85,
    reviewers: [2, 3, 6, 1],
  },
  {
    id: "REQ-4825",
    memberName: "Noor Al-Amiri",
    memberEmail: "noor@municipality.iq",
    avatar: 5,
    template: "Contractor Badge",
    branch: "Erbil North",
    status: "delivered",
    priority: "low",
    submittedAt: "2026-08-06",
    dueAt: "2026-08-20",
    amount: 32500,
    progress: 100,
    reviewers: [5, 2],
  },
  {
    id: "REQ-4826",
    memberName: "Hassan Jaber",
    memberEmail: "h.jaber@municipality.iq",
    avatar: 6,
    template: "Contractor Badge",
    branch: "Erbil North",
    status: "rejected",
    priority: "high",
    submittedAt: "2026-08-06",
    dueAt: "2026-08-21",
    amount: 32500,
    progress: 30,
    reviewers: [1],
  },
  {
    id: "REQ-4827",
    memberName: "Zainab Karim",
    memberEmail: "zainab.karim@ministry.gov",
    avatar: 1,
    template: "Staff ID — Ministry",
    branch: "Najaf Branch",
    status: "in_review",
    priority: "high",
    submittedAt: "2026-08-07",
    dueAt: "2026-08-29",
    amount: 25000,
    progress: 55,
    reviewers: [3, 4, 5],
  },
  {
    id: "REQ-4828",
    memberName: "Ali Mahmoud",
    memberEmail: "ali.m@univ.edu.iq",
    avatar: 2,
    template: "Student ID — Spring",
    branch: "Basra Campus",
    status: "pending",
    priority: "none",
    submittedAt: "2026-08-08",
    dueAt: null,
    amount: 15000,
    progress: 5,
    reviewers: [],
  },
  {
    id: "REQ-4829",
    memberName: "Fatima Salim",
    memberEmail: "f.salim@ministry.gov",
    avatar: 3,
    template: "Visitor Pass",
    branch: "Baghdad Central",
    status: "approved",
    priority: "medium",
    submittedAt: "2026-08-09",
    dueAt: "2026-09-01",
    amount: 8000,
    progress: 65,
    reviewers: [1, 6],
  },
  {
    id: "REQ-4830",
    memberName: "Mustafa Rashid",
    memberEmail: "m.rashid@municipality.iq",
    avatar: 4,
    template: "Contractor Badge",
    branch: "Erbil North",
    status: "printing",
    priority: "low",
    submittedAt: "2026-08-10",
    dueAt: "2026-09-02",
    amount: 32500,
    progress: 90,
    reviewers: [2, 5],
  },
  {
    id: "REQ-4831",
    memberName: "Huda Nasser",
    memberEmail: "huda.nasser@univ.edu.iq",
    avatar: 5,
    template: "Student ID — Spring",
    branch: "Najaf Branch",
    status: "delivered",
    priority: "none",
    submittedAt: "2026-08-11",
    dueAt: "2026-08-24",
    amount: 15000,
    progress: 100,
    reviewers: [3],
  },
  {
    id: "REQ-4832",
    memberName: "Kareem Aziz",
    memberEmail: "kareem.aziz@ministry.gov",
    avatar: 6,
    template: "Staff ID — Ministry",
    branch: "Baghdad Central",
    status: "in_review",
    priority: "medium",
    submittedAt: "2026-08-12",
    dueAt: "2026-09-03",
    amount: 25000,
    progress: 40,
    reviewers: [1, 2, 4, 6],
  },
  {
    id: "REQ-4833",
    memberName: "Rana Tawfiq",
    memberEmail: "rana.t@municipality.iq",
    avatar: 1,
    template: "Visitor Pass",
    branch: "Erbil North",
    status: "pending",
    priority: "low",
    submittedAt: "2026-08-13",
    dueAt: null,
    amount: 8000,
    progress: 15,
    reviewers: [5],
  },
  {
    id: "REQ-4834",
    memberName: "Bilal Saeed",
    memberEmail: "bilal.saeed@univ.edu.iq",
    avatar: 2,
    template: "Student ID — Spring",
    branch: "Basra Campus",
    status: "approved",
    priority: "high",
    submittedAt: "2026-08-14",
    dueAt: "2026-09-04",
    amount: 15000,
    progress: 75,
    reviewers: [2, 3],
  },
  {
    id: "REQ-4835",
    memberName: "Dina Farouk",
    memberEmail: "dina.farouk@ministry.gov",
    avatar: 3,
    template: "Staff ID — Ministry",
    branch: "Najaf Branch",
    status: "rejected",
    priority: "medium",
    submittedAt: "2026-08-15",
    dueAt: "2026-08-30",
    amount: 25000,
    progress: 20,
    reviewers: [4, 1],
  },
  {
    id: "REQ-4836",
    memberName: "Tariq Younis",
    memberEmail: "t.younis@municipality.iq",
    avatar: 4,
    template: "Contractor Badge",
    branch: "Baghdad Central",
    status: "printing",
    priority: "high",
    submittedAt: "2026-08-16",
    dueAt: "2026-09-05",
    amount: 32500,
    progress: 95,
    reviewers: [6, 2, 3],
  },
  {
    id: "REQ-4837",
    memberName: "Maryam Adel",
    memberEmail: "maryam.adel@univ.edu.iq",
    avatar: 5,
    template: "Visitor Pass",
    branch: "Basra Campus",
    status: "delivered",
    priority: "low",
    submittedAt: "2026-08-17",
    dueAt: "2026-08-25",
    amount: 8000,
    progress: 100,
    reviewers: [1, 4, 5],
  },
  {
    id: "REQ-4838",
    memberName: "Samir Qasim",
    memberEmail: "samir.q@ministry.gov",
    avatar: 6,
    template: "Staff ID — Ministry",
    branch: "Erbil North",
    status: "pending",
    priority: "none",
    submittedAt: "2026-08-18",
    dueAt: null,
    amount: 25000,
    progress: 0,
    reviewers: [],
  },
  {
    id: "REQ-4839",
    memberName: "Aya Mansour",
    memberEmail: "aya.mansour@univ.edu.iq",
    avatar: 1,
    template: "Student ID — Spring",
    branch: "Najaf Branch",
    status: "in_review",
    priority: "low",
    submittedAt: "2026-08-19",
    dueAt: "2026-09-06",
    amount: 15000,
    progress: 50,
    reviewers: [3, 6],
  },
  {
    id: "REQ-4840",
    memberName: "Waleed Sabah",
    memberEmail: "waleed.s@municipality.iq",
    avatar: 2,
    template: "Contractor Badge",
    branch: "Baghdad Central",
    status: "approved",
    priority: "medium",
    submittedAt: "2026-08-20",
    dueAt: "2026-09-07",
    amount: 32500,
    progress: 60,
    reviewers: [2, 4, 1],
  },
]
