import type { MemberRequest } from "@/features/members-requests/types"

import type {
  ActivityCell,
  DashboardStatistics,
  MonthlyIdentityCount,
  OrgRank,
  OverviewModel,
  OverviewRange,
  PipelineStage,
  PulsePoint,
  TopOrganization,
} from "./types"

/**
 * The overview screen's whole data layer: `DashboardStatistics` in, one
 * `OverviewModel` out.
 *
 * ### Why this file exists
 *
 * `/statistics` serves eight fields. The screen draws four charts, a ranking,
 * a queue and five tiles. The gap is closed here, in one place, so that:
 *
 *  - no chart component has an opinion about the wire format. They read
 *    `PulsePoint[]`, `PipelineStage[]`, `ActivityCell[]` — shapes chosen for
 *    drawing, not for transport.
 *  - widening the endpoint is a change to this file alone. When the API starts
 *    reporting real dwell times or request timestamps, the synthetic branches
 *    below are deleted and nothing else moves.
 *  - what is measured and what is modelled is decided once, and reported on
 *    the model (`estimated`) rather than left for the reader to guess.
 *
 * ### What is real
 *
 * More than it looks. All five totals, the twelve-month series, the ranking
 * and the queue come straight off the payload, and so does every one of the
 * four pipeline stages — see `derivePipeline`, which builds them out of
 * documented relationships between the totals rather than inventing numbers.
 *
 * ### What is modelled, and how
 *
 * Three things the endpoint cannot answer: median dwell per stage, the
 * weekday × hour activity grid, and pulse buckets finer than a month. Those
 * are generated by `mulberry32` seeded off the real totals — deterministic, so
 * the same tenant always draws the same shape and nothing flickers between
 * renders, and proportional, so a large tenant gets a dense grid. Each is
 * flagged on `model.estimated`, and the UI labels them.
 */

/* ── Deterministic noise ──────────────────────────────────────────────────── */

/**
 * mulberry32 — a seeded 32-bit PRNG.
 *
 * Seeded rather than `Math.random()` because these values are re-derived on
 * every render: an unseeded generator would make the activity grid shimmer
 * whenever anything else on the page changed, and two renders of the same
 * tenant would disagree about which hour was the peak.
 */
function mulberry32(seed: number) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/** A stable seed from the tenant's own numbers, so the shape is theirs. */
function seedFrom(...parts: number[]) {
  return parts.reduce((acc, n) => (acc * 31 + (n || 0)) >>> 0, 7) || 1
}

/* ── Reading the payload ──────────────────────────────────────────────────── */

const num = (value: unknown): number =>
  typeof value === "number" && Number.isFinite(value) ? value : 0

const MONTH_NAMES = [
  "january",
  "february",
  "march",
  "april",
  "may",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
]

/**
 * `month` → a 0-based index, or null.
 *
 * The collection documents `{month,total}` with no example, and the three
 * plausible spellings all type-check against each other: a 1-based number, a
 * month name, or an ISO `2026-09`. Rather than guess one and silently
 * mis-order a year, every form is recognised, and anything unrecognised
 * returns null so the caller can fall back to array position.
 */
export function monthIndexOf(
  month: string | number | null | undefined
): number | null {
  if (typeof month === "number" && Number.isFinite(month)) {
    // 1-based on the wire (January = 1); a 0 is tolerated as already 0-based.
    const index = month >= 1 && month <= 12 ? month - 1 : month
    return index >= 0 && index <= 11 ? index : null
  }
  if (typeof month !== "string") return null

  const text = month.trim().toLowerCase()
  if (!text) return null

  // "2026-09" / "2026-09-01" — take the middle segment.
  const iso = /^(\d{4})-(\d{1,2})(?:-\d{1,2})?/.exec(text)
  if (iso) {
    const index = Number(iso[2]) - 1
    return index >= 0 && index <= 11 ? index : null
  }

  // A bare "9" or "09".
  if (/^\d{1,2}$/.test(text)) {
    const index = Number(text) - 1
    return index >= 0 && index <= 11 ? index : null
  }

  // "September" or "Sep" — a prefix match, so both land on the same row.
  const byName = MONTH_NAMES.findIndex((name) =>
    name.startsWith(text.slice(0, 3))
  )
  return byName >= 0 ? byName : null
}

/**
 * A ranking row's count.
 *
 * Three spellings are accepted because the field is documented only as "an
 * array", and "an organization plus a count" is exactly the kind of shape that
 * differs between endpoints in this API. Reading all three is cheaper than
 * being wrong, and being wrong here draws every bar at zero.
 */
function readOrgTotal(row: TopOrganization): number {
  return num(row.identitiesCount ?? row.totalIdentities ?? row.total)
}

/* ── The twelve-month series ──────────────────────────────────────────────── */

/**
 * `identities_in_year` → twelve totals in calendar order.
 *
 * Normalised onto a fixed twelve-slot calendar rather than trusted as an
 * ordered list: a month the API omits — a tenant's first year — has to read as
 * a real zero in the right slot, not shift every later month one place left.
 * Rows whose `month` is unreadable fall back to their array position, which is
 * the right answer when the API is already sending them in order and the only
 * unrecognised thing is the label format.
 */
function readYearSeries(rows: MonthlyIdentityCount[] | undefined): number[] {
  const byMonth = new Array<number>(12).fill(0)
  if (!Array.isArray(rows)) return byMonth

  rows.forEach((row, position) => {
    const index = monthIndexOf(row?.month) ?? (position <= 11 ? position : null)
    if (index !== null) byMonth[index] += num(row?.total)
  })
  return byMonth
}

/* ── Buckets ──────────────────────────────────────────────────────────────── */

/** How many buckets each range draws, and how wide one bucket is in days. */
const RANGE_SHAPE: Record<OverviewRange, { buckets: number; days: number }> = {
  "30d": { buckets: 30, days: 1 },
  "90d": { buckets: 13, days: 7 },
  "12m": { buckets: 12, days: 30 },
}

/**
 * The pulse series for one range.
 *
 * `12m` is the real thing: the API's own twelve months, rotated so the current
 * month lands last — the order a reader expects from a chart that ends "now".
 *
 * `30d` and `90d` have no source; the endpoint reports monthly totals and
 * nothing finer. Rather than refuse the range or draw a flat line, the
 * window's **real total** is split across its buckets on a weekday rhythm
 * (quiet weekend, a start-of-week peak), so the volume is measured even though
 * the distribution is modelled. `estimated.subMonthly` says so, and the card
 * prints it.
 */
function derivePulse(
  year: number[],
  range: OverviewRange,
  now: Date,
  labelFor: (bucketsBack: number) => string,
  rand: () => number
): PulsePoint[] {
  const currentMonth = now.getMonth()

  if (range === "12m") {
    // Rotate so the series ends on the current month.
    return Array.from({ length: 12 }, (_, i) => {
      const monthIndex = (currentMonth - 11 + i + 24) % 12
      const previousIndex = (monthIndex - 1 + 12) % 12
      return {
        label: labelFor(11 - i),
        value: year[monthIndex],
        // The first point's predecessor is outside the window the API sent.
        previous: i === 0 ? null : year[previousIndex],
        isCurrent: i === 11,
      }
    })
  }

  const { buckets, days } = RANGE_SHAPE[range]
  const monthsCovered = Math.max(1, Math.round((buckets * days) / 30))
  const windowTotal = Array.from(
    { length: monthsCovered },
    (_, i) => year[(currentMonth - i + 24) % 12]
  ).reduce((a, b) => a + b, 0)

  // A weekday rhythm rather than flat noise: intake is an office activity, so
  // the weekend has to dip, or the chart claims something untrue about the week.
  const weights = Array.from({ length: buckets }, (_, i) => {
    const weekday = (now.getDay() - (buckets - 1 - i) * days + 364) % 7
    const office = weekday === 5 || weekday === 6 ? 0.35 : weekday === 0 ? 1.25 : 1
    return office * (0.75 + rand() * 0.5)
  })
  const weightSum = weights.reduce((a, b) => a + b, 0) || 1

  const values = weights.map((w) => Math.round((w / weightSum) * windowTotal))
  return values.map((value, i) => ({
    label: labelFor(buckets - 1 - i),
    value,
    previous: i === 0 ? null : values[i - 1],
    isCurrent: i === buckets - 1,
  }))
}

/* ── The pipeline ─────────────────────────────────────────────────────────── */

/**
 * The four stages of request → card, out of the totals.
 *
 * Every count here is measured, not modelled. The relationships come from the
 * API's own documented semantics:
 *
 *  - **Submitted** = `total_member_requests`. Every application ever made.
 *  - **In review** = submitted − `total_pending_member_requests`. Pending is
 *    defined as *not yet picked up*, so the remainder is what has entered the
 *    review chain.
 *  - **Approved** = `total_members`. `features/members/types.ts` states it
 *    outright: a member exists because a request was approved, and there is no
 *    pending or rejected member.
 *  - **Issued** = `total_identities`. Cards that actually exist.
 *
 * ### The last stage may be wider than the one before it
 *
 * A member can hold more than one card over time — a renewal, a replacement, a
 * second template — so `total_identities` can legitimately exceed
 * `total_members`. The card scales every stage against the **largest** stage
 * rather than the first, so a widening step draws as a widening step, and a
 * loss is printed only where the count actually fell. A funnel that clamped
 * each stage to its predecessor would be drawing a lie to protect a metaphor.
 *
 * `dwellDays` is the one modelled field here: no endpoint carries a duration.
 */
function derivePipeline(
  stats: DashboardStatistics,
  labels: Record<PipelineStage["id"], string>,
  rand: () => number
): PipelineStage[] {
  const submitted = num(stats.totalMemberRequests)
  const pending = num(stats.totalPendingMemberRequests)
  const approved = num(stats.totalMembers)
  const issued = num(stats.totalIdentities)

  const counts: Array<{ id: PipelineStage["id"]; value: number }> = [
    { id: "submitted", value: submitted },
    // Never negative: `pending` is a live queue and `submitted` a lifetime
    // total, and nothing guarantees the API sampled them in the same instant.
    { id: "review", value: Math.max(0, submitted - pending) },
    { id: "approved", value: approved },
    { id: "issued", value: issued },
  ]

  // Plausible medians, longest where a human has to act. Seeded, so a tenant's
  // numbers hold still between renders.
  const dwellBase = [0.4, 2.6, 1.2, 3.1]

  return counts.map((stage, i) => ({
    id: stage.id,
    label: labels[stage.id],
    value: stage.value,
    dropped: i === 0 ? 0 : Math.max(0, counts[i - 1].value - stage.value),
    dwellDays: Number((dwellBase[i] * (0.8 + rand() * 0.45)).toFixed(1)),
  }))
}

/* ── Ranking, activity, queue ─────────────────────────────────────────────── */

/** Rows of the activity grid, Sunday first — see `activity-grid.tsx`. */
const ACTIVITY_DAYS = [0, 1, 2, 3, 4, 5, 6]
/** Two-hour columns, 00:00–02:00 through 22:00–24:00. */
const ACTIVITY_BLOCKS = 12

function deriveOrganizations(rows: TopOrganization[] | undefined): OrgRank[] {
  if (!Array.isArray(rows)) return []
  return rows
    .map((row, i) => ({
      id: num(row.id) || i,
      name: (row.name ?? "").trim(),
      value: readOrgTotal(row),
    }))
    .filter((row) => row.name.length > 0)
    .sort((a, b) => b.value - a.value)
    .slice(0, 6)
}

/**
 * The weekday × two-hour activity grid.
 *
 * Fully modelled — the endpoint reports no timestamps to bin. The shape is an
 * office week rather than noise: a mid-morning ramp, a post-lunch second peak,
 * near-silence overnight and a thin weekend. Scaled by the tenant's real
 * request volume, so a small tenant gets a sparse grid and a large one a dense
 * one, and seeded so "peak hour" is the same fact on every render.
 */
function deriveActivity(totalRequests: number, rand: () => number): ActivityCell[] {
  const empty = () =>
    ACTIVITY_DAYS.flatMap((day) =>
      Array.from({ length: ACTIVITY_BLOCKS }, (_, block) => ({ day, block, value: 0 }))
    )

  // A tenant with no applications has no week to model. Without this guard the
  // bells below still round up to one or two in their busiest cells, and a
  // brand-new organization opens the dashboard to a heat grid implying traffic
  // it has never had — the one failure mode a modelled chart must not have.
  if (totalRequests <= 0) return empty()

  // Two peaks — mid-morning and mid-afternoon — as a sum of two bells.
  const bell = (block: number, centre: number, width: number) =>
    Math.exp(-((block - centre) ** 2) / (2 * width ** 2))

  const cells: ActivityCell[] = []
  const scale = Math.max(1, totalRequests / 320)

  for (const day of ACTIVITY_DAYS) {
    // Rows run Sunday-first (see `ACTIVITY_DAY_ORDER` in the grid), so indices
    // 5 and 6 are Friday and Saturday — the weekend in the region this product
    // ships to, and the same pair `derivePulse` dips.
    const weekend = day === 5 || day === 6
    const dayWeight = weekend ? 0.18 : 1 - day * 0.05

    for (let block = 0; block < ACTIVITY_BLOCKS; block += 1) {
      const shape = bell(block, 5, 1.6) + 0.8 * bell(block, 7.6, 1.4)
      const value = Math.round(shape * dayWeight * scale * (0.6 + rand() * 0.8))
      cells.push({ day, block, value: Math.max(0, value) })
    }
  }
  return cells
}

function deriveLatestRequests(rows: MemberRequest[] | undefined): MemberRequest[] {
  return Array.isArray(rows) ? rows.slice(0, 6) : []
}

/* ── The entry point ──────────────────────────────────────────────────────── */

export type DeriveOptions = {
  range: OverviewRange
  /** Bucket labels, already localised. `back` is how many buckets before now. */
  labelFor: (back: number) => string
  /** Stage names, already localised. */
  stageLabels: Record<PipelineStage["id"], string>
  /** Injected so a test can pin "now". */
  now?: Date
}

export function deriveOverview(
  stats: DashboardStatistics | undefined,
  { range, labelFor, stageLabels, now = new Date() }: DeriveOptions
): OverviewModel {
  const payload = stats ?? {}
  const hasPayload = Object.keys(payload).length > 0

  const totals = {
    identities: num(payload.totalIdentities),
    members: num(payload.totalMembers),
    requests: num(payload.totalMemberRequests),
    pending: num(payload.totalPendingMemberRequests),
    organizations: num(payload.totalOrganizations),
  }

  const year = readYearSeries(payload.identitiesInYear)
  const rand = mulberry32(
    seedFrom(totals.identities, totals.members, totals.requests, totals.organizations)
  )

  const pulse = derivePulse(year, range, now, labelFor, rand)

  /**
   * The delta skips the current bucket, and that is the whole point of it.
   *
   * The last bucket is *in progress* — on the 12th of the month, a monthly
   * series ends on twelve days of data. Comparing that against a complete
   * previous month reported −90.9% on a tenant whose issuance had not changed
   * at all: the chip was measuring the calendar, not the business, and it was
   * measuring it in alarm red.
   *
   * So the comparison is between the last two **complete** buckets. Both are
   * still drawn on the chart, so the number stays one the reader can check
   * with their own eyes, and the partial bucket is rendered differently so it
   * never reads as a collapse (see `pulse-panel.tsx`).
   */
  const complete = pulse.slice(0, -1)
  const last = complete.at(-1)?.value ?? 0
  const previous = complete.at(-2)?.value ?? 0
  const identitiesDelta = previous > 0 ? (last - previous) / previous : null

  return {
    totals,
    identitiesDelta,
    pulse,
    pipeline: derivePipeline(payload, stageLabels, rand),
    organizations: deriveOrganizations(payload.topOrganizations),
    activity: deriveActivity(totals.requests, rand),
    latestRequests: deriveLatestRequests(payload.latestMembersRequests),
    estimated: {
      dwell: true,
      activity: true,
      subMonthly: range !== "12m",
      all: !hasPayload,
    },
  }
}
